export const GET_SUMMARY_COVID19 = "GET_SUMMARY_COVID19";
export const GET_SUMMARY_COVID19_EXITO = "GET_SUMMARY_COVID19_EXITO";
export const GET_SUMMARY_COVID19_ERROR = "GET_SUMMARY_COVID19_ERROR";

export const GET_SUMMARY_COVID19_BY_COUNTRY = "GET_SUMMARY_COVID19_BY_COUNTRY";
export const GET_SUMMARY_COVID19_BY_COUNTRY_EXITO =
  "GET_SUMMARY_COVID19_BY_COUNTRY_EXITO";
export const GET_SUMMARY_COVID19_BY_COUNTRY_ERROR =
  "GET_SUMMARY_COVID19_BY_COUNTRY_ERROR";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SET_NAME_COUNTRY = "SET_NAME_COUNTRY";
export const SET_CODE_COUNTRY = "SET_CODE_COUNTRY";
